module.exports = {
  User: require('./user'),
  Access: require('./access'),
  City: require('./citys'),
  Client: require('./clients'),
  Coupon: require('./coupon'),
  CouponChange: require('./couponsChange'),
  Employeer: require('./employeer'),
  Franchisees: require('./franchisees'),
  Goal: require('./goals'),
  Menu: require('./menu'),
  Message: require('./messages'),
  Notification: require('./notifications'),
  Order: require('./order'),
  PaymentFlow: require('./paymentFlow'),
  Payment: require('./payments'),
  Product: require('./product'),
  Promotion: require('./promotions'),
  Restaurant: require('./restaurant'),
  Row: require('./rows'),
  Story: require('./story'),
  RowsAdditional: require('./rowsAdditional'),
  Categories: require('./categories'),
}
